import React from "react";
import Head from "next/head";
function Layout( { children } ) {
  return (
    <div>
      <Head>
        <title>listTitle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className='font-weight underline'>这个是总入口标题</p>
      {children}
      <footer>版权所有</footer>
    </div>
  );
}
export default Layout;
