import React from "react";
import Head from "next/head";
import { useSelector, connect } from "react-redux";
function Layout( props: any ) {
  const { children } = props;
  console.log('layout重新渲染')
  return (
    <div>
      <Head>
        <title>listTitle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className='font-weight underline'>这个是总入口标题</p>
      {children}
      <footer>版权所有</footer>
    </div>
  );
}
const mapStateToProps = state => ({
  // counter: state.count,
  // person: state.person,
  demoLn: state.lng
});
export default connect(mapStateToProps)(Layout);
// export default Layout;
