import React from "react";
import Head from "next/head";
function List() {
  return (
    <div>
      <Head>
        <title>listTitle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="underline text-xl">Demo</h1>
    </div>
  );
}

export default List;
