import Head from "next/head";
import Link from 'next/link'
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({isDemo}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <Link href="/list">
          <a>list</a>
      </Link>
      {/* 这种形式是属于前端的路由跳转，属于单页面运用，还在当前页面中 */}
      <Link href="/demo">
          <a>demo</a>
      </Link>
      {/* 这种形式类似与向后端路由发送请求，会刷新页面的 */}
      <a href='./list'>跳转</a>
      {isDemo}
    </div>
  );
}
